// Copyright 2016 Jeremy Mason
//
// Licensed under the MIT license <LICENSE or
// http://opensource.org/licenses/MIT>. This file may not be copied, modified,
// or distributed except according to those terms.

//! The only purpose of this crate is to relegate the functions generated by
//! the encode!, decode!, encode_simd! and decode_simd! syntax extensions of
//! pfor_macros to a separate compilation unit. More extensive documentation is
//! given in the pfor_macros crate.

#![feature(plugin)]
#![plugin(pfor_macros)]

extern crate simd;

encode!(u8, 8, 16);
decode!(u8, 8, 16);
encode!(u16, 16, 16);
decode!(u16, 16, 16);
encode!(u32, 32, 16);
decode!(u32, 32, 16);
encode!(u64, 64, 16);
decode!(u64, 64, 16);

encode_simd!(u8, 8, simd::u8x16);
decode_simd!(u8, 8, simd::u8x16);
encode_simd!(u16, 16, simd::u16x8);
decode_simd!(u16, 16, simd::u16x8);
encode_simd!(u32, 32, simd::u32x4);
decode_simd!(u32, 32, simd::u32x4);
encode_simd!(u64, 64, simd::x86::sse2::u64x2);
decode_simd!(u64, 64, simd::x86::sse2::u64x2);
