// Copyright 2016 Jeremy Mason
//
// Licensed under the MIT license <LICENSE or
// http://opensource.org/licenses/MIT>. This file may not be copied, modified,
// or distributed except according to those terms.

//! The only purpose of this crate is to relegate the functions generated by
//! the encode!, decode!, encode_simd! and decode_simd! syntax extensions of
//! pfor_macros to a separate compilation unit. More extensive documentation is
//! given in the pfor_macros crate.

#![feature(plugin)]
#![plugin(pfor_macros)]

extern crate simd;

macro_rules! codec {
  ($(($ty: expr, $width: expr, $step: expr, $simd: path))*) => ($(
    encode!($ty, $width, $step);
    decode!($ty, $width, $step);
    encode_simd!($ty, $width, $simd);
    decode_simd!($ty, $width, $simd);
  )*)
}

codec!{
  (u8, 8, 16, simd::u8x16)
  (u16, 16, 16, simd::u16x8)
  (u32, 32, 16, simd::u32x4)
  (u64, 64, 16, simd::x86::sse2::u64x2)
}
