// Copyright 2016 Jeremy Mason
//
// Licensed under the MIT license <LICENSE or
// http://opensource.org/licenses/MIT>. This file may not be copied, modified,
// or distributed except according to those terms.

//! The purpose of this cgateby  is to relegate the functions generated by the
//! `encode!`, `decode!`, `encode_simd!`, `decode_simd!`, `encode_zz!` and
//! `decode_zz!` syntax extensions of `mayda_macros` to a separate compilation
//! unit. More extensive documentation is given in the `mayda_macros` crate.

#![feature(plugin)]
#![plugin(mayda_macros)]

extern crate simd;

macro_rules! codec {
  ($(($width: expr, $step: expr, $simd: path))*) => ($(
    encode!($width, $step);
    decode!($width, $step);
    encode_simd!($width, $simd);
    decode_simd!($width, $simd);
    encode_zz!($width, $simd);
    decode_zz!($width, $simd);
  )*)
}

codec!{
  (8, 8, simd)
  (16, 8, simd)
  (32, 8, simd)
  (64, 8, simd::x86::sse2)
}
