(function() {var implementors = {};
implementors["simd"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a> for <a class='struct' href='simd/struct.i8x16.html' title='simd::i8x16'>i8x16</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a> for <a class='struct' href='simd/struct.u8x16.html' title='simd::u8x16'>u8x16</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a> for <a class='struct' href='simd/struct.i16x8.html' title='simd::i16x8'>i16x8</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a> for <a class='struct' href='simd/struct.u16x8.html' title='simd::u16x8'>u16x8</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a> for <a class='struct' href='simd/struct.i32x4.html' title='simd::i32x4'>i32x4</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a> for <a class='struct' href='simd/struct.u32x4.html' title='simd::u32x4'>u32x4</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a> for <a class='struct' href='simd/struct.f32x4.html' title='simd::f32x4'>f32x4</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a> for <a class='struct' href='simd/x86/sse2/struct.i64x2.html' title='simd::x86::sse2::i64x2'>i64x2</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a> for <a class='struct' href='simd/x86/sse2/struct.u64x2.html' title='simd::x86::sse2::u64x2'>u64x2</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a> for <a class='struct' href='simd/x86/sse2/struct.f64x2.html' title='simd::x86::sse2::f64x2'>f64x2</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
